more routing more

diff --git a/DockVPN/bin/run b/DockVPN/bin/run
--- a/DockVPN/bin/run
+++ b/DockVPN/bin/run
@@ -66,7 +66,14 @@ dev tun1194
 status openvpn-status-1194.log
 EOF
 
-MY_IP_ADDR=$(curl -s http://icanhazip.com)
+MY_IPV4_ADDR=$(curl -s https://ipv4.icanhazip.com)
+[ "$MY_IP_ADDR" ] || {
+    echo "Sorry, I could not figure out my public IP address."
+    echo "(I use http://myip.enix.org/REMOTE_ADDR/ for that purpose.)"
+    exit 1
+}
+
+MY_IPV6_ADDR=$(curl -s https://ipv6.icanhazip.com)
 [ "$MY_IP_ADDR" ] || {
     echo "Sorry, I could not figure out my public IP address."
     echo "(I use http://myip.enix.org/REMOTE_ADDR/ for that purpose.)"
@@ -94,11 +101,13 @@ redirect-gateway def1
 </dh>
 
 <connection>
-remote $MY_IP_ADDR 1194 udp
+remote $MY_IPV4_ADDR 1194 udp
+remote $MY_IPV6_ADDR 1194 udp
 </connection>
 
 <connection>
-remote $MY_IP_ADDR 443 tcp-client
+remote $MY_IPV4_ADDR 443 tcp-client
+remote $MY_IPV6_ADDR 443 tcp-client
 </connection>
 EOF
 
@@ -111,6 +120,7 @@ Content-Length: `wc -c client.ovpn`
 EOF
 
 iptables -t nat -A POSTROUTING -s 192.168.255.0/24 -o eth0 -j MASQUERADE
+ip6tables -t nat -A POSTROUTING -s 2001:db8:1::/64 -o eth0 -j MASQUERADE
 
 touch tcp443.log udp1194.log http8080.log
 while true ; do openvpn tcp443.conf ; done >> tcp443.log &
